// Automatically generated
const SEGMENT_STATE_KEYS = [
  "value",
  "setValue",
  "segments",
  "dateFormatter",
  "increment",
  "decrement",
  "incrementPage",
  "decrementPage",
  "setSegment",
  "confirmPlaceholder",
  "baseId",
  "unstable_idCountRef",
  "setBaseId",
  "unstable_virtual",
  "rtl",
  "orientation",
  "items",
  "groups",
  "currentId",
  "loop",
  "wrap",
  "unstable_moves",
  "unstable_angular",
  "unstable_hasActiveWidget",
  "registerItem",
  "unregisterItem",
  "registerGroup",
  "unregisterGroup",
  "move",
  "next",
  "previous",
  "up",
  "down",
  "first",
  "last",
  "sort",
  "unstable_setVirtual",
  "setRTL",
  "setOrientation",
  "setCurrentId",
  "setLoop",
  "setWrap",
  "reset",
  "unstable_setHasActiveWidget",
] as const;
export const SEGMENT_KEYS = [
  ...SEGMENT_STATE_KEYS,
  "segment",
  "isDisabled",
  "isReadOnly",
  "isRequired",
] as const;
export const SEGMENT_FIELD_KEYS = SEGMENT_STATE_KEYS;
