// Automatically generated
const SELECT_STATE_KEYS = [
  "baseId",
  "unstable_idCountRef",
  "setBaseId",
  "unstable_virtual",
  "rtl",
  "orientation",
  "items",
  "groups",
  "currentId",
  "loop",
  "wrap",
  "unstable_moves",
  "unstable_angular",
  "unstable_hasActiveWidget",
  "registerItem",
  "unregisterItem",
  "registerGroup",
  "unregisterGroup",
  "move",
  "next",
  "previous",
  "up",
  "down",
  "first",
  "last",
  "sort",
  "unstable_setVirtual",
  "setRTL",
  "setOrientation",
  "setCurrentId",
  "setLoop",
  "setWrap",
  "reset",
  "unstable_setHasActiveWidget",
  "visible",
  "animated",
  "animating",
  "show",
  "hide",
  "toggle",
  "setVisible",
  "setAnimated",
  "stopAnimation",
  "modal",
  "unstable_disclosureRef",
  "setModal",
  "unstable_referenceRef",
  "unstable_popoverRef",
  "unstable_arrowRef",
  "unstable_popoverStyles",
  "unstable_arrowStyles",
  "unstable_originalPlacement",
  "unstable_update",
  "placement",
  "place",
  "allowMultiselect",
  "selected",
  "isPlaceholder",
  "inputValue",
  "isCombobox",
  "values",
  "setInputValue",
  "removeSelected",
  "setSelected",
] as const;
export const SELECT_KEYS = [...SELECT_STATE_KEYS, "onChange"] as const;
export const SELECT_INPUT_KEYS = SELECT_STATE_KEYS;
export const SELECT_MENU_KEYS = SELECT_INPUT_KEYS;
export const SELECT_ITEM_KEYS = [...SELECT_MENU_KEYS, "value"] as const;
export const SELECT_TRIGGER_KEYS = SELECT_MENU_KEYS;
