# .kodiak.toml
version = 1

[merge]
automerge_label = "ready 🎉"
require_automerge_label = false
delete_branch_on_merge = true
optimistic_updates = true
prioritize_ready_to_merge = true
notify_on_conflict = false

[merge.message]
title = "pull_request_title"
body = "github_default"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
