// Automatically generated
export const ACCORDION_KEYS = [] as const;
export const ACCORDION_PANEL_KEYS = ["accordionId"] as const;
export const ACCORDION_TRIGGER_KEYS = [] as const;
const ACCORDION_STATE_KEYS = [
  "setBaseId",
  "registerItem",
  "unregisterItem",
  "registerGroup",
  "unregisterGroup",
  "move",
  "next",
  "previous",
  "up",
  "down",
  "first",
  "last",
  "sort",
  "unstable_setVirtual",
  "setRTL",
  "setOrientation",
  "setCurrentId",
  "setLoop",
  "setWrap",
  "reset",
  "unstable_setHasActiveWidget",
  "select",
  "unSelect",
  "registerPanel",
  "unregisterPanel",
  "baseId",
  "unstable_idCountRef",
  "unstable_virtual",
  "rtl",
  "orientation",
  "items",
  "groups",
  "currentId",
  "loop",
  "wrap",
  "unstable_moves",
  "unstable_angular",
  "unstable_hasActiveWidget",
  "manual",
  "allowToggle",
  "panels",
  "allowMultiple",
] as const;
