export const ACCORDION_KEYS = [
  "baseId",
  "unstable_idCountRef",
  "setBaseId",
  "items",
  "registerItem",
  "buttons",
  "registerButton",
  "panels",
  "registerPanel",
  "activeItems",
  "addActiveItem",
  "removeActiveItem",
  "allowMultiple",
  "allowToggle",
  "defaultActiveId",
  "manual",
  "loop",
  "next",
  "prev",
] as const;
