// Automatically generated
const TIME_PICKER_COLUMN_STATE_KEYS = [
  "baseId",
  "unstable_idCountRef",
  "setBaseId",
  "unstable_virtual",
  "rtl",
  "orientation",
  "items",
  "groups",
  "currentId",
  "loop",
  "wrap",
  "unstable_moves",
  "unstable_angular",
  "unstable_hasActiveWidget",
  "registerItem",
  "unregisterItem",
  "registerGroup",
  "unregisterGroup",
  "move",
  "next",
  "previous",
  "up",
  "down",
  "first",
  "last",
  "sort",
  "unstable_setVirtual",
  "setRTL",
  "setOrientation",
  "setCurrentId",
  "setLoop",
  "setWrap",
  "reset",
  "unstable_setHasActiveWidget",
  "selected",
  "setSelected",
] as const;
const TIME_PICKER_STATE_KEYS = [
  "baseId",
  "unstable_idCountRef",
  "setBaseId",
  "unstable_virtual",
  "rtl",
  "orientation",
  "items",
  "groups",
  "currentId",
  "loop",
  "wrap",
  "unstable_moves",
  "unstable_angular",
  "unstable_hasActiveWidget",
  "registerItem",
  "unregisterItem",
  "registerGroup",
  "unregisterGroup",
  "move",
  "next",
  "previous",
  "up",
  "down",
  "first",
  "last",
  "sort",
  "unstable_setVirtual",
  "setRTL",
  "setOrientation",
  "setCurrentId",
  "setLoop",
  "setWrap",
  "reset",
  "unstable_setHasActiveWidget",
  "hours",
  "minutes",
  "meridies",
  "hourState",
  "minuteState",
  "meridiesState",
] as const;
export const TIME_PICKER_KEYS = [
  ...TIME_PICKER_COLUMN_STATE_KEYS,
  ...TIME_PICKER_STATE_KEYS,
] as const;
export const TIME_PICKER_COLUMN_KEYS = TIME_PICKER_KEYS;
export const TIME_PICKER_COLUMN_VALUE_KEYS = [
  ...TIME_PICKER_COLUMN_KEYS,
  "value",
] as const;
