// Automatically generated
const CALENDER_STATE_KEYS = [
  "up",
  "down",
  "next",
  "previous",
  "weeksDays",
  "weeks",
  "previousMonth",
  "previousYear",
  "nextMonth",
  "nextYear",
  "selectedDate",
  "setSelectedDate",
  "startDate",
  "baseId",
  "unstable_idCountRef",
  "setBaseId",
  "unstable_virtual",
  "rtl",
  "orientation",
  "items",
  "groups",
  "currentId",
  "loop",
  "wrap",
  "unstable_moves",
  "unstable_angular",
  "unstable_hasActiveWidget",
  "registerItem",
  "unregisterItem",
  "registerGroup",
  "unregisterGroup",
  "move",
  "first",
  "last",
  "sort",
  "unstable_setVirtual",
  "setRTL",
  "setOrientation",
  "setCurrentId",
  "setLoop",
  "setWrap",
  "reset",
  "unstable_setHasActiveWidget",
] as const;
export const CALENDER_KEYS = CALENDER_STATE_KEYS;
export const CALENDER_BODY_KEYS = CALENDER_KEYS;
export const CALENDER_CELL_KEYS = [...CALENDER_BODY_KEYS, "date"] as const;
export const CALENDER_ROW_KEYS = CALENDER_BODY_KEYS;
