export const INTERACTION_KEYS = [
  "isDisabled",
  "onFocusChange",
  "autoFocus",
  "isTextInput",
  "onFocusVisibleChange",
  "onFocusWithin",
  "onBlurWithin",
  "onFocusWithinChange",
  "onHoverStart",
  "onHoverChange",
  "onHoverEnd",
  "onPress",
  "onPressChange",
  "onPressStart",
  "onPressEnd",
  "onPressUp",
  "elementType",
] as const;
