export const data = [
  {
    name: "meter state initial state",
    in: {},
    out: {
      high: 1,
      low: 0,
      max: 1,
      min: 0,
      optimum: 0.5,
      percent: 0,
      status: "safe",
      value: 0,
    },
  },
  {
    name: "meter state with value",
    in: { value: 0.5 },
    out: {
      high: 1,
      low: 0,
      max: 1,
      min: 0,
      optimum: 0.5,
      percent: 50,
      status: "safe",
      value: 0.5,
    },
  },
  {
    name: "meter state with custom props",
    in: {
      min: 0,
      low: 2.5,
      value: 5,
      high: 7.5,
      max: 10,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 5,
      percent: 50,
      status: "safe",
      value: 5,
    },
  },

  {
    name: "meter state with optimum < min",
    in: {
      min: 0,
      low: 2.5,
      value: 5,
      high: 7.5,
      max: 10,
      optimum: -5,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 0,
      percent: 50,
      status: "caution",
      value: 5,
    },
  },

  {
    name: "meter state with optimum > max",
    in: {
      min: 0,
      low: 2.5,
      value: 5,
      high: 7.5,
      max: 10,
      optimum: 15,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 10,
      percent: 50,
      status: "caution",
      value: 5,
    },
  },

  {
    name: "meter state with optimum between low & high and value at same range",
    in: {
      min: 0,
      low: 2.5,
      value: 5,
      high: 7.5,
      max: 10,
      optimum: 5,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 5,
      percent: 50,
      status: "safe",
      value: 5,
    },
  },

  {
    name: "meter state with optimum between low & high and value below low",
    in: {
      min: 0,
      low: 2.5,
      value: 2,
      high: 7.5,
      max: 10,
      optimum: 5,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 5,
      percent: 20,
      status: "caution",
      value: 2,
    },
  },

  {
    name: "meter state with optimum between low & high and value above high",
    in: {
      min: 0,
      low: 2.5,
      value: 8,
      high: 7.5,
      max: 10,
      optimum: 5,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 5,
      percent: 80,
      status: "caution",
      value: 8,
    },
  },

  {
    name: "meter state with optimum at high",
    in: {
      min: 0,
      low: 2.5,
      value: 5,
      high: 7.5,
      max: 10,
      optimum: 7.5,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 7.5,
      percent: 50,
      status: "safe",
      value: 5,
    },
  },

  {
    name: "meter state with optimum at low",
    in: {
      min: 0,
      low: 2.5,
      value: 5,
      high: 7.5,
      max: 10,
      optimum: 2.5,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 2.5,
      percent: 50,
      status: "safe",
      value: 5,
    },
  },

  {
    name: "meter state with optimum < low & >= min and value at same range",
    in: {
      min: 0,
      low: 2.5,
      value: 0,
      high: 7.5,
      max: 10,
      optimum: 2,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 2,
      percent: 0,
      status: "safe",
      value: 0,
    },
  },

  {
    name: "meter state with optimum < low & >= min and value > low",
    in: {
      min: 0,
      low: 2.5,
      value: 5,
      high: 7.5,
      max: 10,
      optimum: 2,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 2,
      percent: 50,
      status: "caution",
      value: 5,
    },
  },

  {
    name: "meter state with optimum < low & >= min and value > high",
    in: {
      min: 0,
      low: 2.5,
      value: 8,
      high: 7.5,
      max: 10,
      optimum: 2,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 2,
      percent: 80,
      status: "danger",
      value: 8,
    },
  },

  {
    name: "meter state with optimum <= max & >= high & value at same range",
    in: {
      min: 0,
      low: 2.5,
      value: 8,
      high: 7.5,
      max: 10,
      optimum: 9,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 9,
      percent: 80,
      status: "safe",
      value: 8,
    },
  },

  {
    name: "meter state with optimum <= max & >= high & value < high",
    in: {
      min: 0,
      low: 2.5,
      value: 5,
      high: 7.5,
      max: 10,
      optimum: 9,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 9,
      percent: 50,
      status: "caution",
      value: 5,
    },
  },

  {
    name: "meter state with optimum <= max & >= high & value < low",
    in: {
      min: 0,
      low: 2.5,
      value: 2,
      high: 7.5,
      max: 10,
      optimum: 9,
    },
    out: {
      high: 7.5,
      low: 2.5,
      max: 10,
      min: 0,
      optimum: 9,
      percent: 20,
      status: "danger",
      value: 2,
    },
  },
];
