name: bundlesize

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, reopened]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: install deps
        run: yarn
      - name: Build
        run: yarn build:umd

      - name: "Comment PR"
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { exec } = require("child_process");
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            exec(`yarn bundlesize`, (error, stdout, stderr) => {
              if (error) { console.log(error); return};
              if (stderr) { console.log(stderr); return};
              github.issues.createComment({ issue_number, owner, repo, body: stdout });
            });
